// GENERATED by orbis_codegen. Do not edit.
//
// Registering by hand means writing a name, a kind and an
// arity that have to agree with the class and with whatever
// the other end of a network session registered. Generating
// it removes that whole class of mismatch.

import 'dart:typed_data';

import 'package:orbis_core/orbis_core.dart';

/// Every component this package declares, against one world.
///
/// Registration is idempotent, so two packages declaring the
/// same component with the same layout resolve to one id.
class OrbisSimulationExampleComponents {
  OrbisSimulationExampleComponents.register(World world)
      : networkId = world.registerComponent('NetworkId', kind: ComponentKind.int64, arity: 1),
        velocity = world.registerComponent('Velocity', kind: ComponentKind.float32, arity: 3);

  /// NetworkId — int64 x1 (value).
  final ComponentType networkId;

  /// Velocity — float32 x3 (x, y, z).
  final ComponentType velocity;

  /// Every declared component.
  List<ComponentType> get all => [
        networkId,
        velocity,
      ];

  /// The components that cross the wire.
  List<ComponentType> get replicated => [
        velocity,
      ];

  /// Components an owning client may write.
  Set<String> get ownerWritable => const {'Velocity'};
}

/// Typed access to a NetworkId column.
///
/// An extension type, so this costs nothing at run time — it
/// is the same list with names on its offsets.
extension type NetworkIdColumn(Int64List data) {
  /// How many entities the column holds.
  int get length => data.length ~/ 1;

  int value(int row) => data[row * 1];
  void setValue(int row, int value) => data[row * 1] = value;
}

/// Typed access to a Velocity column.
///
/// An extension type, so this costs nothing at run time — it
/// is the same list with names on its offsets.
extension type VelocityColumn(Float32List data) {
  /// How many entities the column holds.
  int get length => data.length ~/ 3;

  double x(int row) => data[row * 3];
  void setX(int row, double value) => data[row * 3] = value;

  double y(int row) => data[row * 3 + 1];
  void setY(int row, double value) => data[row * 3 + 1] = value;

  double z(int row) => data[row * 3 + 2];
  void setZ(int row, double value) => data[row * 3 + 2] = value;
}

